#Write an input python code that will ask for your name, designation, emailaddress, phone number and print the details
print("What is your Name")
Name=input()
print("what is your Designation")
Designation=input()
print("Email_address")
Email_address=input()
print("Phone_number")
Phone_number=input()
print("These are my details:" + Name + "," + Designation + "," + Email_address + "," + Phone_number)